# Generated by Django 4.1.3 on 2022-11-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('job_categorey', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('job_sub_categorey', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('job_categorey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobData.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobData.companydetail')),
                ('job_sub_categorey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobData.subcategorie')),
            ],
        ),
        migrations.AddField(
            model_name='companydetail',
            name='job_sub_categorey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobData.subcategorie'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobData.state'),
        ),
    ]
