# Generated by Django 4.1 on 2022-11-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('job_categorey', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('job_sub_categorey', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('job_categorey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.companydetail')),
                ('job_sub_categorey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.subcategorie')),
            ],
        ),
        migrations.AddField(
            model_name='companydetail',
            name='job_sub_categorey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.subcategorie'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.state'),
        ),
    ]
