# Generated by Django 4.1.3 on 2022-11-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_companydetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
