# Generated by Django 4.1.3 on 2022-11-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_companydetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='job_position',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
