# Generated by Django 4.1.3 on 2022-11-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_jobdetail_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
